PetAdoptionMVC/Models/PetMaster.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PetAdoptionMVC.Models
{
    public class PetMaster
    {
        [Key]
        public int PetId { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Pet Name can't be longer than 100 characters.")]
        public string PetName { get; set; }


        [Required]
        [Range(0, 100, ErrorMessage = "Age must be between 0 and 100.")]
        public int Age { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "Gender can't be longer than 10 characters.")]
        public string Gender { get; set; }

        [Required(ErrorMessage = "Price is required.")]
        [Range(0, 10000, ErrorMessage = "Price must be between 0 and 10,000.")]
        public decimal Price { get; set; }


        [Required(ErrorMessage = "Please upload a pet image.")]
        public string PetImage { get; set; }

        [Required]
        public string Description { get; set; }


        [Required]
        [StringLength(20, ErrorMessage = "Status can't be longer than 20 characters.")]
        public string Status { get; set; }

        public bool ActiveFlag { get; set; } = true;


        // Navigation Properties

        public int PetCategoryId { get; set; }
        [ForeignKey("PetCategoryId")]
        public virtual PetCategoryMaster PetCategoryMaster { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public virtual PetBehaviorProfile PetBehaviorProfile { get; set; }

        public ICollection<AdoptionRequest> AdoptionRequests { get; set; }

    }
}

PetAdoptionMVC/Controllers/AdoptionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using PetAdoptionMVC.Models;

namespace PetAdoptionMVC.Controllers
{
    public class AdoptionController : Controller
    {
        private readonly PetAdoptionContext _context;

        public AdoptionController(PetAdoptionContext context)
        {
            _context = context;
        }
        public IActionResult MyAdoptionRequests()
        {
           
            // Fetch the adoption requests for the logged-in user.
            var adoptionRequests = _context.AdoptionRequests
                .Include(r => r.Pet) // Include Pet details
                .Where(r => r.UserId == (int)HttpContext.Session.GetInt32("Id"))
                .OrderByDescending(r => r.RequestDate)
                .ToList();

            return View(adoptionRequests); // Pass the data to the View.
        }



        [HttpGet]
        public IActionResult CreateAdoptionRequest(int petId)
        {
           


            var adoptionRequest = new AdoptionRequest
            {
                RequestDate = DateTime.Now,
                Status = "Pending Approval",
                ActiveFlag = true,
                UserId = (int)HttpContext.Session.GetInt32("Id"),
                PetId = petId
            };

            _context.AdoptionRequests.Add(adoptionRequest);
            _context.SaveChanges();

            NotifyAdmin(adoptionRequest);

            return RedirectToAction("RequestSuccess");
        }

        private void NotifyAdmin(AdoptionRequest request)
        {
            // Notification logic to admin
            Console.WriteLine($"Admin notified of new adoption request: Request ID = {request.RequestId}");
        }

        public IActionResult RequestSuccess()
        {
            return View(); // Display success message
        }

    }
}

PetAdoptionMVC/Controllers/PetMastersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PetAdoptionMVC.Models;

namespace PetAdoptionMVC.Controllers
{
    public class PetMastersController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly PetAdoptionContext _context;


        public PetMastersController(PetAdoptionContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: PetMasters
        public async Task<IActionResult> AllPetDetails()
        {
            var pets = await _context.PetMasters
                                     .Include(p => p.PetCategoryMaster)
                                     .Include(p => p.PetBehaviorProfile) // Include Behavior Profile
                                     .Include(p => p.AdoptionRequests)  // Include Adoption Requests
                                     .ToListAsync();

            return View(pets);
        }

        // Details Action to View Pet Details
        public async Task<IActionResult> PetDetails(int id)
        {
            var pet = await _context.PetMasters
                                     .Include(p => p.PetCategoryMaster)
                                     .Include(p => p.PetBehaviorProfile)
                                     .Include(p => p.AdoptionRequests)
                                     .FirstOrDefaultAsync(p => p.PetId == id);

            if (pet == null) return NotFound();

            return View(pet);
        }

        public async Task<IActionResult> Index()
        {
            var petAdoptionContext = _context.PetMasters.Include(p => p.PetCategoryMaster);
            return View(await petAdoptionContext.ToListAsync());
        }

        // GET: PetMasters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PetMasters == null)
            {
                return NotFound();
            }

            var petMaster = await _context.PetMasters
                .Include(p => p.PetCategoryMaster)
                .FirstOrDefaultAsync(m => m.PetId == id);
            if (petMaster == null)
            {
                return NotFound();
            }

            return View(petMaster);
        }

        // GET: PetMasters/Create
        public IActionResult Create()
        {
            ViewBag.PetCategoryId = new SelectList(_context.PetCategoryMasters, "CategoryId", "CategoryName");
            ViewBag.GenderOptions = new SelectList(new[] { "Male", "Female", "Others" });
            ViewBag.StatusOptions = new SelectList(new[] { "Available", "Not Available" });

            return View(new PetMaster());
        }

        // POST: PetMasters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PetMaster petMaster)
        {
            //if (ModelState.IsValid)
            //{
            //    string uniqueFileName = UploadedFile(petMaster);
            //    petMaster.PetImage = uniqueFileName;
            //    _context.Attach(petMaster);
            //    _context.Entry(petMaster).State = EntityState.Added;
            //    _context.SaveChanges();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["PetCategoryId"] = new SelectList(_context.PetCategoryMasters, "CategoryId", "CategoryName", petMaster.PetCategoryId);
            //return View(petMaster);
            string uniqueFileName = UploadedFile(petMaster);
            petMaster.PetImage = uniqueFileName;
            _context.Attach(petMaster);
            _context.Entry(petMaster).State = EntityState.Added;
            _context.SaveChanges();
            ViewBag.PetCategoryId = new SelectList(_context.PetCategoryMasters, "CategoryId", "CategoryName", petMaster.PetCategoryId);
            ViewBag.GenderOptions = new SelectList(new[] { "Male", "Female", "Others" }, petMaster.Gender);
            ViewBag.StatusOptions = new SelectList(new[] { "Available", "Not Available" }, petMaster.Status);
            return RedirectToAction(nameof(Index));
        }
        private string UploadedFile(PetMaster petMaster)
        {
            string uniqueFileName = null;
            if (petMaster.ImageFile != null)
            {
                string uploadsfolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + petMaster.ImageFile.FileName;
                string filePath = Path.Combine(uploadsfolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    petMaster.ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;

        }

        // GET: PetMasters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var petMaster = await _context.PetMasters.FindAsync(id);
            if (petMaster == null)
            {
                return NotFound();
            }

            ViewBag.PetCategoryId = new SelectList(_context.PetCategoryMasters, "CategoryId", "CategoryName", petMaster.PetCategoryId);
            ViewBag.GenderOptions = new SelectList(new[] { "Male", "Female", "Others" }, petMaster.Gender);
            ViewBag.StatusOptions = new SelectList(new[] { "Available", "Not Available" }, petMaster.Status);

            return View(petMaster);
        }

        // POST: PetMasters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PetMaster petMaster)
        {
            if (id != petMaster.PetId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string uniqueFileName = UploadedFile(petMaster);
                    if (!string.IsNullOrEmpty(uniqueFileName))
                    {
                        petMaster.PetImage = uniqueFileName;
                    }

                    _context.Update(petMaster);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PetMasterExists(petMaster.PetId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.PetCategoryId = new SelectList(_context.PetCategoryMasters, "CategoryId", "CategoryName", petMaster.PetCategoryId);
            ViewBag.GenderOptions = new SelectList(new[] { "Male", "Female", "Others" }, petMaster.Gender);
            ViewBag.StatusOptions = new SelectList(new[] { "Available", "Not Available" }, petMaster.Status);

            return View(petMaster);
        }

        // GET: PetMasters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PetMasters == null)
            {
                return NotFound();
            }

            var petMaster = await _context.PetMasters
                .Include(p => p.PetCategoryMaster)
                .FirstOrDefaultAsync(m => m.PetId == id);
            if (petMaster == null)
            {
                return NotFound();
            }

            return View(petMaster);
        }

        // POST: PetMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PetMasters == null)
            {
                return Problem("Entity set 'PetAdoptionContext.PetMasters'  is null.");
            }
            var petMaster = await _context.PetMasters.FindAsync(id);
            if (petMaster != null)
            {
                _context.PetMasters.Remove(petMaster);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PetMasterExists(int id)
        {
            return _context.PetMasters.Any(e => e.PetId == id);
        }

        [HttpPost]
        public IActionResult SearchByCategory(int PetCategoryId)
        {
            List<PetMaster> pets;
            if (PetCategoryId == 0)
            {
                // If 0, fetch all products
                pets = _context.PetMasters.ToList();
            }
            else
            {
                // Fetch products by selected category
                pets = _context.PetMasters.Where(p => p.PetCategoryId == PetCategoryId).ToList();
            }

            ViewData["PetCategoryId"] = new SelectList(_context.PetMasters, "PetCategoryId", "CategoryName");
            return View("Index1", pets);
        }

        [HttpGet("ByCategory/{categoryId}")]
        public async Task<IActionResult> GetProductsByCategory(int PetCategoryId)
        {
            var products = await _context.PetMasters.Where(p => p.PetCategoryId == PetCategoryId).ToListAsync();
            return Ok(Index);


        }

        [HttpGet]

PetAdoptionMVC/Views/PetMasters/AllPetDetails.cshtml
@{
    ViewData["Title"] = "AllPetDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<PetAdoptionMVC.Models.PetMaster>

<h2>All Pet Details</h2>

<div class="pets-container">
    @foreach (var pet in Model)
    {
        <div class="pet-card">
            <div class="pet-image">
                <img src="@Url.Content("~/images/" + pet.PetImage)" alt="@pet.PetName" />
            </div>
            <div class="pet-info">
                <h3 class="pet-name">Name:@pet.PetName</h3>
                <p class="pet-details">Age:@pet.Age |Gender: @pet.Gender</p>
                <p class="pet-status">Status:@pet.Status</p>
                <p class="pet-category">Breed:@pet.PetCategoryMaster.CategoryName</p>
                <p class="pet-description">Description:@pet.Description</p>

            </div>
            <div class="pet-actions">
                <a asp-action="PetDetails" asp-route-id="@pet.PetId" class="btn btn-primary">Details</a>
                <a asp-action="CreateAdoptionRequest" asp-controller="Adoption" asp-route-petId="@pet.PetId" class="btn btn-success">Adopt Now</a>
            </div>
        </div>
    }
</div>
<style>
    .pets-container {
        display: flex;
        flex-wrap: wrap;
        gap: 20px;
        justify-content: center;
    }

    .pet-card {
        border: 1px solid #ccc;
        border-radius: 8px;
        width: 250px;
        background: #fff;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        overflow: hidden;
        text-align: center;
        font-family: Arial, sans-serif;
    }

        .pet-card .pet-image img {
            width: 100%;
            height: auto;
        }

    .pet-info {
        padding: 15px;
    }

        .pet-info .pet-name {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .pet-info .pet-details,
        .pet-info .pet-status,
        .pet-info .pet-category,
        .pet-info .pet-description,
        .pet-info .pet-owner {
            margin: 5px 0;
            font-size: 0.9em;
            color: #666;
        }

    .pet-actions {
        display: flex;
        justify-content: space-evenly;
        padding: 15px;
        background-color: #f9f9f9;
    }

        .pet-actions .btn {
            font-size: 0.9em;
            padding: 8px 12px;
            border-radius: 4px;
            text-decoration: none;
            color: #fff;
        }

        .pet-actions .btn-primary {
            background-color: #007bff;
        }

        .pet-actions .btn-success {
            background-color: #28a745;
        }

        .pet-actions .btn:hover {
            opacity: 0.8;
        }
</style>

PetAdoptionMVC/Views/PetMasters/Create.cshtml
@model PetAdoptionMVC.Models.PetMaster
@{
    ViewData["Title"] = "Add New Pet";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="form-container">
    <h1>Add a New Pet</h1>
    <h4>Fill out the form to add a new pet to the adoption list.</h4>
    <form asp-action="Create" enctype="multipart/form-data">
        <!-- Pet Name -->
        <div class="form-group">
            <label asp-for="PetName">Pet Name <span class="text-danger">*</span></label>
            <input asp-for="PetName" class="form-control" placeholder="Enter the pet's name" />
            <span asp-validation-for="PetName" class="text-danger"></span>
        </div>

        <!-- Age -->
        <div class="form-group">
            <label asp-for="Age">Age (in years) <span class="text-danger">*</span></label>
            <input asp-for="Age" class="form-control" placeholder="Enter the pet's age" />
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>

        <!-- Gender -->
        <div class="form-group">
            <label asp-for="Gender">Gender <span class="text-danger">*</span></label>
            <select asp-for="Gender" asp-items="ViewBag.GenderOptions" class="form-control">
                <option value="">-- Select Gender --</option>
            </select>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>

        <!-- Description -->
        <div class="form-group">
            <label asp-for="Description">Description <span class="text-danger">*</span></label>
            <textarea asp-for="Description" class="form-control" placeholder="Describe the pet (e.g., temperament, likes, dislikes)" rows="4"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <!-- Status -->
        <div class="form-group">
            <label asp-for="Status">Adoption Status <span class="text-danger">*</span></label>
            <select asp-for="Status" asp-items="ViewBag.StatusOptions" class="form-control">
                <option value="">-- Select Status --</option>
            </select>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>

        <!-- Category -->
        <div class="form-group">
            <label asp-for="PetCategoryId">Pet Category <span class="text-danger">*</span></label>
            <select asp-for="PetCategoryId" asp-items="ViewBag.PetCategoryId" class="form-control">
                <option value="">-- Select Category --</option>
            </select>
            <span asp-validation-for="PetCategoryId" class="text-danger"></span>
        </div>

        <!-- Price -->
        <div class="form-group">
            <label asp-for="Price">Price<span class="text-danger">*</span></label>
            <input asp-for="Price" class="form-control" placeholder="Enter the pet's Price" />
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>

        <!-- Image Upload -->
        <div class="form-group">
            <label asp-for="ImageFile">Upload Pet Image</label>
            <input asp-for="ImageFile" type="file" class="form-control" />
            <small class="form-text text-muted">Accepted formats: JPEG, PNG. Max size: 5MB.</small>
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>

        <!-- Submit Button -->
        <button type="submit" class="btn-submit">Add Pet</button>
    </form>

    <!-- Back Link -->
    <div class="back-link">
        <a asp-action="Index">Back to List</a>
    </div>
</div>

<style>
    /* Form Styling */
    .form-container {
        max-width: 600px;
        margin: 0 auto;
        background: #ffffff;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

        .form-container h1 {
            text-align: center;
            color: #4caf50;
            font-size: 2rem;
            margin-bottom: 20px;
        }

        .form-container h4 {
            text-align: center;
            color: #666;
            font-size: 1.2rem;
            margin-bottom: 30px;
        }

    .form-group {
        margin-bottom: 15px;
    }

        .form-group label {
            font-size: 1rem;
            color: #333;
            font-weight: 600;
        }

        .form-group input,
        .form-group select,
        .form-group textarea {
            width: 100%;
            padding: 12px;
            font-size: 1rem;
            color: #333;
            border: 1px solid #ccc;
            border-radius: 5px;
            transition: all 0.3s;
        }

            .form-group input:focus,
            .form-group select:focus,
            .form-group textarea:focus {
                border-color: #4caf50;
                outline: none;
                box-shadow: 0 0 5px rgba(76, 175, 80, 0.5);
            }

    .btn-submit {
        display: block;
        width: 100%;
        padding: 12px;
        font-size: 1.1rem;
        font-weight: bold;
        color: white;
        background: #4caf50;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: all 0.3s;
    }

        .btn-submit:hover {
            background: #388e3c;
        }

    .back-link {
        text-align: center;
        margin-top: 20px;
        font-size: 1rem;
        color: #4caf50;
    }

        .back-link a {
            text-decoration: none;
            color: #4caf50;
        }

            .back-link a:hover {
                text-decoration: underline;
            }
</style>

PetAdoptionMVC/Views/PetMasters/Delete.cshtml
    @model PetAdoptionMVC.Models.PetMaster

    @{
        ViewData["Title"] = "Delete Pet";
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }

    @if (Model == null)
    {
        <div class="alert alert-warning text-center my-4">
            Pet not found.
        </div>
    }
    else
    {
        <h1 class="text-danger text-center">Delete Pet</h1>

        <h4 class="text-center">Are you sure you want to delete this pet?</h4>
        <hr />

        <div class="card my-4 shadow-sm">
            <div class="card-body">
                <h3 class="card-title text-primary">@Model.PetName</h3>
                <p><strong>Category:</strong> @Model.PetCategoryMaster?.CategoryName</p>
                <p><strong>Gender:</strong> @Model.Gender</p>
                <p><strong>Status:</strong> @Model.Status</p>
                <p><strong>Description:</strong> @Model.Description</p>
                <div>
                    @if (!string.IsNullOrEmpty(Model.PetImage))
                    {
                        <img src="@Url.Content("~/images/" + Model.PetImage)" alt="Pet Image" class="img-thumbnail" style="max-width: 150px;" />
                    }
                    else
                    {
                        <span class="text-muted">No Image Available</span>
                    }
                </div>
            </div>
        </div>

        <form asp-action="Delete" method="post" class="mt-4">
            @Html.AntiForgeryToken()
            <input type="hidden" asp-for="PetId" />
            <div class="d-flex justify-content-between">
                <button type="submit" class="btn btn-danger btn-submit">Delete</button>
                <a asp-action="Index" asp-controller="PetMasters" class="btn btn-secondary btn-submit">Cancel</a>
            </div>
        </form>
    }

    <style>
        h1.text-danger {
            font-size: 2rem;
            font-weight: bold;
        }

        h4.text-center {
            font-size: 1.2rem;
            color: #666;
        }

        .card-body {
            background-color: #f9f9f9;
        }

        .card-title {
            font-size: 1.5rem;
            font-weight: bold;
            color: #007bff;
        }

        .card-body p {
            font-size: 1rem;
            color: #333;
        }

        .card-body img {
            border: 2px solid #ddd;
            border-radius: 5px;
        }

        .text-muted {
            color: #888;
        }

        .d-flex {
            display: flex;
            justify-content: space-between;
        }

        .btn-submit {
            padding: 12px;
            font-size: 1.1rem;
            font-weight: bold;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: all 0.3s;
        }

        .btn-danger {
            background: #e74c3c;
        }

            .btn-danger:hover {
                background: #c0392b;
            }

        .btn-secondary {
            background: #f1f1f1;
            color: #333;
        }

            .btn-secondary:hover {
                background: #ddd;
            }
    </style>

PetAdoptionMVC/Views/PetMasters/Edit.cshtml
@model PetAdoptionMVC.Models.PetMaster
@{
    ViewData["Title"] = "Edit Pet";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit Pet</h1>
<h4>Pet Master</h4>
<hr />

<form asp-action="Edit" method="post" enctype="multipart/form-data">

    <!-- IMPORTANT: Hidden Keys -->
    <input type="hidden" asp-for="PetId" />
    <input type="hidden" asp-for="PetImage" />

    <div class="form-group">
        <label asp-for="PetName" class="control-label"></label>
        <input asp-for="PetName" class="form-control" />
        <span asp-validation-for="PetName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PetCategoryId" class="control-label"></label>
        <select asp-for="PetCategoryId" class="form-control" asp-items="ViewBag.PetCategoryId"></select>
        <span asp-validation-for="PetCategoryId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Gender" class="control-label"></label>
        <select asp-for="Gender" class="form-control" asp-items="ViewBag.GenderOptions"></select>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Status" class="control-label"></label>
        <select asp-for="Status" class="form-control" asp-items="ViewBag.StatusOptions"></select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>

    <!-- CURRENT IMAGE SHOW -->
    <div class="form-group">
        <label>Current Image</label><br />
        @if (Model.PetImage != null)
        {
            <img src="~/images/@Model.PetImage" width="180" style="border-radius:10px;" />
        }
        else
        {
            <p>No Image</p>
        }
    </div>

    <!-- NEW IMAGE UPLOAD -->
    <div class="form-group">
        <label asp-for="ImageFile" class="control-label"></label>
        <input type="file" asp-for="ImageFile" class="form-control" />
        <span asp-validation-for="ImageFile" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a href="@Url.Action("Index", "PetMasters")" class="btn btn-secondary">Cancel</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PetAdoptionMVC/Views/PetMasters/Index.cshtml
@model List<PetAdoptionMVC.Models.PetMaster>

@{
    ViewData["Title"] = "All Pets";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="form-container">
    <h2>All Pets</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Pet Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Category</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pet in Model)
            {
                <tr>
                    <td>@pet.PetName</td>
                    <td>@pet.Age</td>
                    <td>@pet.Gender</td>
                    <td>@pet.PetCategoryMaster?.CategoryName</td>
                    <td>@pet.Status</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@pet.PetId" class="btn-submit btn-warning">Edit</a>
                        <a asp-action="Delete" asp-route-id="@pet.PetId" class="btn-submit btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-action="Create" class="btn-submit btn-primary">Add New Pet</a>
</div>

<style>
    /* Table Styling */
    .table {
        width: 100%;
        margin-top: 20px;
        border-collapse: collapse;
    }

        .table th,
        .table td {
            padding: 12px;
            text-align: left;
            border: 1px solid #ddd;
        }

        .table th {
            background-color: #f2f2f2;
            color: #333;
            font-weight: 600;
        }

        .table td {
            color: #555;
        }

    /* Button Styling */
    .btn-submit {
        display: inline-block;
        padding: 12px;
        font-size: 1.1rem;
        font-weight: bold;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: all 0.3s;
        text-align: center;
        margin-right: 10px;
    }

        .btn-submit:hover {
            opacity: 0.8;
        }

    .btn-primary {
        background: #4caf50;
    }

        .btn-primary:hover {
            background: #388e3c;
        }

    .btn-warning {
        background: #ff9800;
    }

        .btn-warning:hover {
            background: #fb8c00;
        }

    .btn-danger {
        background: #f44336;
    }

        .btn-danger:hover {
            background: #d32f2f;
        }
</style>